name = "NativeFileDialog"
uuid = "e1fe445b-aa65-4df4-81c1-2041507f0fd4"
authors = ["José Joaquín Zubieta Rico <jose.zubieta@cimat.mx> and contributors"]
version = "0.2.0"

[deps]
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
NativeFileDialog_jll = "94d9ae2c-efc7-56f8-9a02-54c47b797961"

[compat]
FilePathsBase = "0.9"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
